### ISSUE TITLE
Use of imprecise data types bool instead of bool?

### ISSUE THREAD

**Issue by AP-G** [microsoft/OpenAPI.NET#519]
Among other things I am using the this component to convert between the different API versions and representations. Unfortunately some information gets lost, especially with some boolean values. 

The reason is that some properties are currently modelled as bool instead of bool? it cannot be differentiated, if a value was set before or not. In the writer-Source it is solved by hardcoding default-values and ommitting the write step if the boolean value and the default value are equal. While this works well for the writer this information gets lost in the global objects and cannot be used in other tools. Or the hard-codings have to be re-done. 

It would be much nicer to replace the bool by bool? and add a function for getting the default value, if not set. This way the default values need only to be implemented once and the information is not lost. It is even possible to create a backwards-compatible version returning a bool with the default value if the bool? is null...

For example in OpenApiSchema bool? is used several times like with `UniqueItems`

Only bool is used at least for the following properties:
`OpenApiParameter.AllowReserved
OpenApiParameter.AllowEmptyValue
OpenApiParameter.Deprecated
OpenApiParameter.Explode
OpenApiParameter.Required

OpenApiHeader.AllowReserved
OpenApiHeader.AllowEmptyValue
OpenApiHeader.Deprecated
OpenApiHeader.Explode
OpenApiHeader.Required

OpenApiRequestBody.Required

OpenApiSchema.AdditionalPropertiesAllowed
OpenApiSchema.Nullable
OpenApiSchema.Deprecated
OpenApiSchema.ReadOnly
OpenApiSchema.WriteOnly
`

**Comment by darrelmiller** [comment]
Hey @AP-G thanks for raising this issue.  How about if we implemented IsXXXDefault functions for all properties that have a non-null default?

**Comment by baywet** [comment]
Hi @AP-G

This is something we've greatly improved with version 2 and 3 of the library (support for OpenAPI 3.1 and 3.2):
- Proper roundtrip of the document
- Avoid emitting defaults

I encourage you to try again on the latest versions, and report any issue remaining. 

Here is an analysis validating the properties you've mentioned are initialized with the correct defaults.

Let us know if you have any additional comments or questions.

Functionally, **absence is equivalent to `false` for most listed boolean flags**, but not always equivalent for round-tripping intent because the current object model often cannot distinguish “explicitly set to false” from “not present”.

| Property | Current code type | Spec/default behavior | Is absence functionally identical to `false` / `null`? |
| --- | --- | --- | --- |
| `OpenApiParameter.AllowReserved` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiParameter.AllowEmptyValue` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiParameter.Deprecated` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiParameter.Explode` | public `bool`, private `bool? _explode` | Default is `true` for `form` / `cookie`, otherwise `false` | **Yes functionally**, but not always equal to literal `false`; absence means “use style-dependent default”. |
| `OpenApiParameter.Required` | `bool` | For `path`, required and MUST be `true`; otherwise default `false` | **Yes for non-path parameters**. **No for path parameters**, where absence is invalid. |
| `OpenApiHeader.Required` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiHeader.Deprecated` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiHeader.Explode` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiHeader.AllowReserved` | `bool` | Not a Header Object field in OAS 3.2 | **Not applicable by OAS 3.2**; if emitted as an extension-like extra field, absence is not the same as a defined spec `false`. |
| `OpenApiHeader.AllowEmptyValue` | `bool` | Not a Header Object field in OAS 3.2 | **Not applicable by OAS 3.2**. |
| `OpenApiRequestBody.Required` | `bool` | OAS 3.2 default is `false` | **Yes**, functionally absent == `false`. |
| `OpenApiSchema.AdditionalPropertiesAllowed` | `bool`, default `true` | JSON Schema says omitting `additionalProperties` has the same assertion behavior as `{}` | **No for `false`**. Absence is functionally equivalent to allowing additional properties / empty schema, not to `false`. |
| `OpenApiSchema.Nullable` | No current public property; OAS 3.0 compatibility is represented through `type` including `null` | OAS 3.2 uses JSON Schema type unions, e.g. `type: ["string", "null"]`; `nullable` is not an OAS 3.2 Schema Object keyword | **Not applicable in OAS 3.2**. Absence does not mean nullable; nullability must be expressed in the schema type. |
| `OpenApiSchema.Deprecated` | `bool` | JSON Schema 2020-12 says omitting `deprecated` behaves as `false` | **Yes**, functionally absent == `false`. |
| `OpenApiSchema.ReadOnly` | `bool` | JSON Schema 2020-12 says omitting `readOnly` behaves as `false` | **Yes**, functionally absent == `false`. |
| `OpenApiSchema.WriteOnly` | `bool` | JSON Schema 2020-12 says omitting `writeOnly` behaves as `false` | **Yes**, functionally absent == `false`. |

So the short answer is: **for validation/serialization behavior, most missing boolean fields are intentionally equivalent to their default value, usually `false`; however, that does not mean the object model can preserve whether the author explicitly wrote `false` or omitted the field.** If consumers need round-tripping or intent preservation, nullable backing state is still useful even when the functional interpretation is identical.

The main exceptions are:

1. `additionalProperties`: absence is equivalent to an empty schema / allowed additional properties, not `false`.
2. `explode`: absence means the style-dependent default, not always literal `false`.
3. path parameter `required`: must be `true`; absence is invalid.
4. schema `nullable`: not an OAS 3.2 keyword in the current model; nullability is represented through JSON Schema types.
5. header `allowReserved` / `allowEmptyValue`: not defined fields on the OAS 3.2 Header Object.
